# Generated by Django 3.2.7 on 2021-09-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=200)),
                ('time', models.DateTimeField(null=True)),
                ('won', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Irregularity',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=400)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('classifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.classifier')),
                ('procuring_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('bidders', models.ManyToManyField(through='flags.Bid', to='flags.Entity')),
                ('classifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.classifier')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(null=True)),
                ('irregularity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.irregularity')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.lot')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.entity'),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.lot'),
        ),
    ]
