# Generated by Django 3.2.7 on 2021-09-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flags.tender'),
        ),
        migrations.AlterField(
            model_name='irregularity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='irregularity',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
