# Generated by Django 3.2.7 on 2022-04-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_auto_20210909_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='irregularity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', related_query_name='flags_test', to='flags.irregularity'),
        ),
    ]
